function [INDEX,TRACKID,VALID,UTCDATE,UTCTIME,LOCALDATE,LOCALTIME,MS,LATITUDE,NS,LONGITUDE,EW,ALTITUDE,SPEED,HEADING,GX,GY,GZ] = importgps(filename, startRow, endRow)
%   This file is part of DataGoal: a Matlab Toolbox to Linear and Non-linear Soccer Positional Data Analysis.
%   Copyright (C) 2024 Bruno L. S. Bedo, Felipe A. Moura, Rodrigo Aquino, Sérgio A. Cunha, Paulo R. P. Santiago
% 
%   Licensed under the Apache License, Version 2.0 (the "License");
%   you may not use this file except in compliance with the License.
%   You may obtain a copy of the License at
% 
%       http://www.apache.org/licenses/LICENSE-2.0
% 
%   Unless required by applicable law or agreed to in writing, software
%   distributed under the License is distributed on an "AS IS" BASIS,
%   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%   See the License for the specific language governing permissions and
%   limitations under the License.
%
%   Bruno L. S. Bedo,
%   <bruno.bedo@usp.br>
% 
% Author:   Bruno Luiz Souza Bedo <bruno.bedo@usp.br> %IMPORTGPS Import numeric data from a text file as column vectors.
%   [INDEX,TRACKID,VALID,UTCDATE,UTCTIME,LOCALDATE,LOCALTIME,MS,LATITUDE,NS,LONGITUDE,EW,ALTITUDE,SPEED,HEADING,GX,GY,GZ]
%   = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [INDEX,TRACKID,VALID,UTCDATE,UTCTIME,LOCALDATE,LOCALTIME,MS,LATITUDE,NS,LONGITUDE,EW,ALTITUDE,SPEED,HEADING,GX,GY,GZ]
%   = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [INDEX,TRACKID,VALID,UTCDATE,UTCTIME,LOCALDATE,LOCALTIME,MS,LATITUDE,NS,LONGITUDE,EW,ALTITUDE,SPEED,HEADING,GX,GY,GZ] = importfile1('JR_U15_21-03 - GPS_7.csv',2, 3992);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/23 14:11:59

% Initialize variables.
    delimiter = ',';
    if nargin<=2
        startRow = 2;
        endRow = inf;
    end

    % Format for each line of text:
    %   column1: double (%f)
    %	column2: double (%f)
    %   column3: text (%q)
    %	column4: text (%q)
    %   column5: datetimes (%{HH:mm:ss}D)
    %	column6: text (%q)
    %   column7: datetimes (%{HH:mm:ss}D)
    %	column8: double (%f)
    %   column9: double (%f)
    %	column10: text (%q)
    %   column11: double (%f)
    %	column12: text (%q)
    %   column13: double (%f)
    %	column14: double (%f)
    %   column15: double (%f)
    %	column16: double (%f)
    %   column17: double (%f)
    %	column18: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%f%q%q%{HH:mm:ss}D%q%{HH:mm:ss}D%f%f%q%f%q%f%f%f%f%f%f%[^\n\r]';

    % Open the text file.
    fileID = fopen(filename,'r');

    % Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end

    % Close the text file.
    fclose(fileID);

    % Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    % Allocate imported array to column variable names
    INDEX = dataArray{:, 1};
    TRACKID = dataArray{:, 2};
    VALID = dataArray{:, 3};
    UTCDATE = dataArray{:, 4};
    UTCTIME = dataArray{:, 5};
    LOCALDATE = dataArray{:, 6};
    LOCALTIME = dataArray{:, 7};
    MS = dataArray{:, 8};
    LATITUDE = dataArray{:, 9};
    NS = dataArray{:, 10};
    LONGITUDE = dataArray{:, 11};
    EW = dataArray{:, 12};
    ALTITUDE = dataArray{:, 13};
    SPEED = dataArray{:, 14};
    HEADING = dataArray{:, 15};
    GX = dataArray{:, 16};
    GY = dataArray{:, 17};
    GZ = dataArray{:, 18};

    % For code requiring serial dates (datenum) instead of datetime, uncomment
    % the following line(s) below to return the imported dates as datenum(s).

    % UTCTIME=datenum(UTCTIME);
    % LOCALTIME=datenum(LOCALTIME);
    end