function data = importVectorS7(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   TREINO21 = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   TREINO21 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Treino21 = importfile('Treino 21.07.2022 Export for Jeferson J 80947.csv', 10, 52979);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2022/12/15 17:22:05

%% Initialize variables.
    delimiter = {' ',';'};
    if nargin<=2
        startRow = 10;
        endRow = inf;
    end

    %% Format for each line of text:
    %   column1: text (%q)
    %	column2: text (%q)
    %   column3: text (%q)
    %	column4: text (%q)
    %   column5: text (%q)
    %	column6: text (%q)
    %   column7: text (%q)
    %	column8: text (%q)
    %   column9: text (%q)
    %	column10: text (%q)
    %   column11: text (%q)
    %	column12: text (%q)
    %   column13: text (%q)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%*s%*s%*s%*s%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r','n','UTF-8');
    % Skip the BOM (Byte Order Mark).
    fseek(fileID, 3, 'bof');

    %% Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.
    %% Create output variable
    data = [dataArray{1:end-1}];
    data = data(:,[2,7:8]); 
end 

