function rawdata = importStatsSports(filename, dataLines)
% This file is part of DataGoal Toolbox: 
% 
% Author:   Bruno Luiz Souza Bedo <bruno.bedo@usp.br> 
%  IMPORTFILE Import data from a text file
%  rawdata =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a string array.
%
%  rawdata =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  rawdata = importfile("D:\Documents\USP\LaBioCom\Processamento - GUI_GPS\GPS_Data\StatsSports\Session 20-7-2019\Session-Henrique Milagres-20-7-2019 Session-Henrique Milagres-20-7-2019_RawData.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Jul-2020 15:36:49

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["PlayerId", "PlayerDisplayName", "Time", "ElapsedTimes", "Lat", "Lon", "Speedkmh", "InstantaneousAccelerationImpulse", "HeartRatebpm"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
rawdata = readtable(filename, opts);

%% Convert to output type
rawdata = table2array(rawdata);
end